from my.wafutil import *

def build(bld):

  c_compile('getenv1.c getenv2.c getenv3.c')

  c_program_list('atfork suspend',
                 uselib_local = 'apue',
                 )

  c_program('timeout',
            'timeout.c detach.c',
            uselib_local = 'apue',
            )
