def build(bld):
    bld.objects(source='getenv1.c getenv2.c getenv3.c', use='apue_includes')
    for target in 'atfork suspend'.split():
        bld.program(source=target + '.c', target=target,
                    lib='pthread', use='apue')
    bld.program(source='timeout.c detach.c', target='timeout',
                lib='pthread', use='apue')
