from my.wafutil import *

def build(bld):

  c_static_library('ipp_util',
                   'util.c')

  c_program('print',
            'print.c',
            lib = 'pthread',
            uselib_local = 'apue clconn ipp_util',
            )

  c_program('printd',
            'printd.c',
            lib = 'pthread',
            uselib_local = 'apue clconn initsrv2 ipp_util',
            )
