def build(bld):
    bld.stlib(source='util.c', target='ipp_util', use='apue_includes')
    bld.program(source='print.c', target='print',
                lib='pthread', use='apue clconn ipp_util')
    bld.program(target='printd', source='printd.c',
                lib = 'pthread', use ='apue clconn initsrv2 ipp_util')
