from my.wafutil import *

def build(bld):
  c_compile('initsrv1.c recvfd.c sendfd.c'
            ' cliconn.c servlisten.c servaccept.c spipe.c')

  c_library('initsrv2',
            'initsrv2.c')

  c_library('clconn',
            'clconn.c')

  c_program('ruptime',
            'ruptime.c',
            uselib_local = 'apue clconn',
            )

  c_program_list('ruptimed ruptimed-fd ruptimed-dg',
                 uselib_local = 'apue initsrv2',
                 )

  c_program_list('findsvc bo ruptime-dg bindunix',
                 uselib_local = 'apue',
                 )
