def build(bld):
    bld.objects(source='initsrv1.c recvfd.c sendfd.c'
                       ' cliconn.c servlisten.c servaccept.c spipe.c',
                use='apue_includes')
    bld.shlib(source='initsrv2.c', target='initsrv2', use='apue_includes')
    bld.shlib(source='clconn.c', target='clconn', use='apue_includes')

    for target in 'ruptimed ruptimed-fd ruptimed-dg'.split():
        bld.program(source=target + '.c', target=target, use='apue initsrv2')

    for target in 'findsvc bo ruptime-dg bindunix'.split():
        bld.program(source=target + '.c', target=target, use='apue')
