def build(bld):

  source = ('childdial.c cliargs.c client.c ctlstr.c debug.c devfile.c dialfile.c'
            ' expectstr.c lock.c loop.c main.c request.c sendstr.c sigchld.c'
            ' sysfile.c ttydial.c ttyopen.c')

  bld(features = 'cc cprogram',
      source = source,
      target = 'calld',
      lib = 'pthread',
      uselib_local = ['apue', 'clconn', 'initsrv2',],
      )
