from my.wafutil import *

def build(bld):

  c_program_list('critical mask read1 read2 reenter sigtstp'
                 ' sigusr suspend1 suspend2',
                 uselib_local = 'apue',
                 )

  c_compile('abort.c sleep1.c system.c')

  c_program('tsleep2',
            'sleep2.c tsleep2.c',
            uselib_local = 'apue',
            )
