def build(bld):
    for target in ('critical mask read1 read2 reenter sigtstp'
                   ' sigusr suspend1 suspend2').split():
        bld.program(source=target + '.c', target=target, use='apue')

    bld.objects(source='abort.c sleep1.c system.c')
    bld.program(source='sleep2.c tsleep2.c', target='tsleep2', use='apue')
