def build(bld):
    bld.objects(source='sleep.c sleepus_poll.c sleepus_select.c asyncsocket.c',
                use='apue_includes')
    bld.program(source='goodexit.c openmax.c', target='goodexit',
                lib='pthread', use='apue')
    for target in 'getpw44bsd getlogin sizepipe'.split():
        bld.program(source=target + '.c', target=target, use='apue')
