from my.wafutil import *

def build(bld):

  c_compile('sleep.c sleepus_poll.c sleepus_select.c asyncsocket.c')

  c_program('goodexit',
            'goodexit.c openmax.c',
            lib = 'pthread',
            uselib_local = 'apue',
            )

  c_program_list('getpw44bsd getlogin sizepipe',
                 uselib_local = 'apue',
                 )
