def build(bld):

  progs = 'doatexit testjmp'

  for prog in progs.split():
    bld(features = 'cc cprogram',
        source = prog + '.c',
        target = prog,
        uselib_local = ['apue',],
        )
