def build(bld):
    for target in ('echoall echoarg exec1 exec2 fork1 fork2 pruids shell1 shell2'
                   ' systest3 tellwait1 tellwait2 test1 times1 vfork1 vfork3 wait1 zombie').split():
        bld.program(source=target + '.c', target=target, use='apue')

    bld.stlib(source='system.c', target='proc_system')

    for target in 'systest1 systest2'.split():
        bld.program(source=target + '.c', target=target, use='apue proc_system')

    bld.program(source='pracct.c', target='pracct',
                defines=['HAS_AXIS', 'HAS_ACORE',],
                use='apue')
