from my.wafutil import *

def build(bld):

  c_program_list('access cdpwd changemod fileflags filetype ftw4'
                 ' hello hole longpath ls1 mycd seek testerror'
                 ' uidgid umask unlink zap',
                 uselib_local = 'apue',
                 )
