def build(bld):

  bld(rule   = 'cp ${SRC} ${TGT}',
      source = 'bsd_ptyopen.c',
      target = 'ptyopen.c',
      )

  source = ('bufargs.c cliconn.c clrfl.c'
            ' daemonize.c error.c errorlog.c lockreg.c locktest.c'
            ' openmax.c pathalloc.c popen.c prexit.c prmask.c'
            ' ptyfork.c ptyopen.c readn.c recvfd.c'
            ' senderr.c sendfd.c servaccept.c servlisten.c'
            ' setfl.c signal.c signalintr.c'
            ' sleepus.c spipe.c'
            ' tellwait.c ttymodes.c writen.c') # sleep.o pathconf.o sysconf.o'

  bld(features = 'cc cshlib',
      source = source,
      target = 'apue')
