from my.wafutil import *

def build(bld):

  # extern loop
  c_static_library('opend',
                   'client.c main.c request.c',
                   uselib_local = 'apue opend.fe_cliargs',
                   )

  c_program('opend.poll',
            'loop.poll.c',
            uselib_local = 'apue opend opend.fe_cliargs',
            )

  c_program('opend.select',
            'loop.select.c',
            uselib_local = 'apue opend opend.fe_cliargs',
            )
