def build(bld):
    # extern loop
    bld.stlib(source='client.c main.c request.c', target='opend',
              use='apue opend.fe_cliargs')
    bld.program(source='loop.poll.c', target='opend.poll',
                use='apue opend opend.fe_cliargs')
    bld.program(source='loop.select.c', target='opend.select',
                use='apue opend opend.fe_cliargs')
