def build(bld):

  bld(features = 'cc cshlib',
      source = 'db.c',
      target = 'db',
      uselib_local = ['apue',],
      )

  bld(features = 'cc cprogram',
      source = 't4.c',
      target = 't4',
      uselib_local = ['apue', 'db'],
      )
