from my.wafutil import *

def build(bld):

  c_library('db',
            'db.c',
            uselib_local = 'apue',
            )

  c_library('t4',
            't4.c',
            uselib_local = 'apue db',
            )
