def build(bld):
    # extern err_msg, etc.
    bld.stlib(source='cliargs.c', target='opend.fe_cliargs',
              use='apue_includes')
    bld.program(source='main.c request.c', target='opend.fe_opend',
                use='apue opend.fe_cliargs')
