from my.wafutil import *

def build(bld):

  # extern err_msg, etc.
  c_static_library('opend.fe_cliargs',
                   'cliargs.c',
                   )

  c_program('opend.fe_opend',
            'main.c request.c',
            uselib_local = ['apue', 'opend.fe_cliargs',],
            )
