from my.wafutil import *

def build(bld):

  c_compile('condvar.c mutex1.c mutex2.c mutex3.c rwlock.c')

  c_program_list('threadid exitstatus cleanup badexit2',
                 uselib_local = ['apue',],
                 )
