def build(bld):
    bld.objects(source='condvar.c mutex1.c mutex2.c mutex3.c rwlock.c')
    for target in 'threadid exitstatus cleanup badexit2'.split():
        bld.program(source=target + '.c', target=target, lib='pthread', use='apue')
