def build(bld):
    bld.objects(source='ctermid.c')
    bld.program(source='t_isatty.c isatty.c', target='t_isatty', use='apue')
    bld.program(source='t_ttyname.c ttyname.c', target='t_ttyname', use='apue')
    bld.program(source='t_getpass.c getpass.c', target='t_getpass', use='apue')
    for target in 'csize settty t_raw winch'.split():
        bld.program(source=target + '.c', target=target, use='apue')
