from my.wafutil import *

def build(bld):

  c_compile('ctermid.c')

  c_program('t_isatty',
            't_isatty.c isatty.c',
            uselib_local = 'apue',
            )

  c_program('t_ttyname',
            't_ttyname.c ttyname.c',
            uselib_local = 'apue',
              )

  c_program('t_getpass',
            't_getpass.c getpass.c',
            uselib_local = 'apue',
            )

  c_program_list('csize settty t_raw winch',
                 uselib_local = 'apue',
                 )
