from my.wafutil import *

def build(bld):

  # extern csopen
  c_static_library('open.fe_main',
                   'main.c',
                   )

  c_program('openclient',
            'open.c',
            uselib_local = 'apue open.fe_main',
          )
